name: AuthMePE
main: AuthMePE\AuthMePE
api: 1.12.0
version: 0.1.7_beta
author: hoyinm & CyberCube-HK™
description: Port of most features of Bukkit's AuthMe_Reloaded

commands:
  unregister:
    usage: /unregister
    description: Unregister your LoginSecurity account
    permission: authmepe.command.unregister
    aliases: ["rmpass"]
  changepass:
    usage: /changepass <old> <new> <new>
    description: change your password
    permission: authmepe.command.changepass
    aliases: ["changepassword", "changepw"]
  email:
    usage: /email <mail>
    description: Add your email
    permission: authmepe.command.email
  logout:
    usage: /logout
    description: Logs out from your account
    permission: authmepe.command.logout
  authme:
    usage: /authme changepass|unregister <args...>
    description: Admin command
    permission: authmepe.command.authme
    aliases: ["authmepe"]

permissions:
  authmepe.command.unregister:
    default: true
  authmepe.command.changepass:
    default: true
  authmepe.command.email:
    default: true
  authmepe.command.logout:
    default: true
  authmepe.command.authme:
    default: op
  authmepe.login.bypass:
    default: false
