name: LoginSecurity
main: LoginSecurity\LoginSecurity
api: 1.12.0
version: 0.5.01004
author: hoyinm
update: Many things..

commands:
  unregister:
    usage: /unregister
    description: Unregister your LoginSecurity account
    permission: loginsecurity.command.unregister
    aliases: ["rmpass"]
  changepass:
    usage: /changepass <old> <new> <new>
    description: change your password
    permission: loginsecurity.command.changepass
    aliases: ["changepassword", "changepw"]
  email:
    usage: /email <mail>
    description: Add your email
    permission: loginsecurity.command.email

permissions:
  loginsecurity.command.unregister:
    default: true
  loginsecurity.command.changepass:
    default: true
  loginsecurity.command.email:
    default: true
    
