name: AuthMePE
main: AuthMePE\AuthMePE
api: 3.0.0-ALPHA5
version: 1.0.0
author: hoyinm14mc, Edwardthedog2
description: Port of most features of Bukkit's AuthMe_Reloaded

commands:
  unregister:
    usage: /unregister
    description: Unregister your LoginSecurity account
    permission: authmepe.command.unregister
    aliases: ["rmpass"]
  changepass:
    usage: /changepass <old> <new> <new>
    description: change your password
    permission: authmepe.command.changepass
    aliases: ["changepassword", "changepw"]
  chgemail:
    usage: /chgemail <mail>
    description: Add your email
    permission: authmepe.command.chgemail
    aliases: ["setemail", "email"]
  logout:
    usage: /logout
    description: Logs out from your account
    permission: authmepe.command.logout
  authme:
    usage: /authme help
    description: Admin command
    permission: authmepe.command.authme
    aliases: ["authmepe"]

permissions:
  authmepe.command.unregister:
    default: true
  authmepe.command.changepass:
    default: true
  authmepe.command.chgemail:
    default: true
  authmepe.command.logout:
    default: true
  authmepe.command.authme:
    default: op
  authmepe.login.bypass:
    default: false
